import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
  <>
  <Head>
    <title>Home - Rian Prastio</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <main>

    {/* Jumbotron */}
    <section id="profile">
      <div className="container">

        <div className="col-sm">

          <div className="row">
            <div className="jumbotron text-center bgImage">
              <div className="wrapper-profile">

                <div className="image-wrapper">
                  <Image
                    src="/picture/my_prof.jfif"
                    alt="My Profile"
                    layout="fill"
                    objectFit="cover"
                  />
                </div>
                <h1>Rian Prastio</h1>
                <p>Software Engineer | Android Developer | Fullstack Developer | Web Developer | Office Administration</p>
              </div>
            </div>

          </div>
        

        </div>
      </div>
    </section>
    {/* End Jumbotron */}

    {/* About */}
    <section id="about">
      <div className="container">

        <div className="col-sm">
          <h2 className="text-center">Tentang Saya</h2>
          <div className="underline-txt"></div>
        </div>

        <div className="row align-center text-left justify-center">

          <div className="col-sm col-sm-offset-1">
            <p>Saya adalah siswa yang terampil pada bidang programming dan pengembangan (developing) yang berspesialisasi dalam pengembangan fullstack. Berpengalaman dengan semua tahap developing seperti problem solving dalam software dan maintaining software. Terampil dalam menggunakan berbagai bahasa Program serta Hypertext program tersebut diantaranya yaitu: Javascript (React JS, Next JS, Node JS, Jquery, Object Oriented Javascript), HTML5 & CSS3, Python, PHP (Laravel), C# (XAML, WPF), C++ (GTKMM), LUA, Android Studio (Kotlin), Database (MySQL, MongoDB, SQL Server), Operation System (Windows, Linux).</p>
          </div>

          <div className="col-sm">
            <p>Dan saya memiliki ilmu keterampilan dalam perkantoran seperti Microsoft Office (Word, Excel, PowerPoint), Manajemen Dokumen dan Data, Menjurnalkan Dokumen, Penginputan melalui Google Spread Sheet, dan kemampuan lainnya yang menyangkut tentang Administrasi Perkantoran seperti menggunakan Telepon Kantor, Menjurnal dengan buku agenda, Print dokumen dan Scan dokumen. Dan saya mempunyai latar belakang yang kuat dalam melakukan pengembangan suatu projek software sehingga menjadikan saya pribadi yang kreatif, disiplin, berkomitmen tinggi, dapat bekerja dalam bentuk tim ataupun individual dan serta saya mampu mengerjakan pekerjaan secara tepat waktu.</p>
          </div>

        </div>
      </div>
      
    </section>
    {/* End About */}


    {/* Skill */}
    <section id="skill">
      <div className="container">
        
        <div className="col-sm">
          <h2 className="text-center">Kemampuan & Keahlian</h2>
          <div className="underline-txt"></div>
        </div>


        <div className="row align-center justify-center skills-list">
          
          <div className="col-sm">

            <h5>Hard Skill</h5>
            <button className="collapsible">Javascript</button>
            <div className="content">
              <h6>Runtime Environment</h6><hr/>
              <p>Node.js</p>

              <h6>Framework</h6><hr/>
              <p>Node.js</p>
              <p>Next.js</p>
              <p>React.js</p>
              <p>Express.js</p>
              <p>Fastify.js</p>
              <p>Bootstrap</p>
              <p>Jquery</p>
              
              <h6>Library</h6><hr/>
              <p>React.js</p>
              <p>Jquery</p>
              <p>Moment.js</p>

              <h6>Database</h6><hr/>
              <p>MongoDB</p>
              <p>MySQL</p>

              <p>Object Oriented Programming Javascript</p>
            </div>

            <p>HTML5 & CSS3</p>
            <p>Python</p>

            <button className="collapsible">PHP</button>
            <div className="content">
              <h6>Framework</h6><hr/>
              <p>Laravel</p>

              <h6>Database</h6><hr/>
              <p>phpMyAdmin</p>
              <p>MySQL</p>
            </div>

            <button className="collapsible">C#</button>
            <div className="content">
              <p>.NET</p>
              <p>XAML</p>
              <p>WPF</p>
              <p>Microsoft SQL Server</p>
            </div>

            <button className="collapsible">C++</button>
            <div className="content">
              <p>GTKMM</p>
            </div>

            <button className="collapsible">Android Developer</button>
            <div className="content">
              <p>Kotlin</p>
            </div>
            
            <p>LUA</p>

            <button className="collapsible">Operation System</button>
            <div className="content">
              <p>Windows</p>
              <p>Linux</p>
            </div>

            <button className="collapsible">Microsoft Office</button>
            <div className="content">
              <p>Word</p>
              <p>Excel</p>
              <p>PowerPoint</p>
            </div>

            <p>Google Spread Sheet</p>
            
            <p>Manajemen Dokumen dan Data</p>
            <p>Menjurnalkan Dokumen</p>
            <p>Menggunakan Telepon Kantor</p>
            <p>Menjurnal dengan buku agenda</p>
            <p>Print dan Scan Dokumen</p>

            <p>Mengetik 10 jari</p>


          </div>

          <div className="col-sm">
            <h5>Soft Skill</h5>

            <p>Berbahasa inggris dengan aktif dan pasif</p>
            <p>Pandai dalam bersosialisasi serta berkomunikasi dengan baik</p>
            <p>Public Speaking</p>
            <p>Mampu bekerja dalam tim ataupun individual</p>
            <p>Mampu beradpatasi</p>
            <p>Kemauan tinggi untuk belajar</p>
            <p>Berfikir kritis</p>
            <p>Empati</p>
            <p>Kreatif</p>
            <p>Disiplin</p>
            <p>Berkomitmen tinggi</p>
            <p>Sopan dan santun</p>
            <p>Cepat tanggap</p>
            <p>Serta mampu mengerjakan pekerjaan secara tepat waktu</p>

          </div>
          
          

        </div>

      </div>
    </section>
    {/* End Skill */}



    {/* Pengalaman */}
    <section id="pengalaman">
      <div className="container">
        
        <div className="col-sm">
          <h2 className="text-center">Pengalaman</h2>
          <div className="underline-txt"></div>
        </div>

        <div className="container-pengalaman">
          <p><strong>PT Pengerukan Indonesia</strong> (Jakarta, Indonesia)</p>
          <p><strong>Praktik Kerja Lapangan, Subdit SDM</strong> (Januari 2022 – Maret 2022)</p>

          <ul>
            <li>
              Membantu para staf/karyawan dan pembimbing dalam mengerjakan pekerjaannya seperti membantu membuatkan dokumen, membuat jadwal meeting, mengedit surat perjalanan dinas, membuat Rencana Anggaran Biaya, Melayani tamu yang berkunjung ke kantor, membantu menginput data, menjurnalkan data, mengantarkan dokumen, merekap kehadiran para pegawai serta anak pkl dan magang dalam sebulan, dan membantu mengarsip file pembimbing serta para staf lainnya yang meminta bantuan dalam mengarsipkan filenya.
            </li>

            <li>
              Membantu HRD dalam memilih calon pekerjanya hingga memeriksa 1000 dalam mencari orang yang memiliki ahli dibidang Staf Surveyor dan Staf Permesinan (Engineering).
            </li>
              
            <li>
              Membantu HRD dalam melakukan draf insentif PKL dan Magang serta melakukan draf laporan kegiatan PKL dan Magang.
            </li>
              
          </ul>
        </div>

        <div className="container-pengalaman">
          <p><strong>TEFA</strong> (Jakarta, Indonesia)</p>
          <p><strong>Praktik Kerja Lapangan, Marketing</strong> (Desember 2021 - Januari 2022)</p>

          <ul>
            <li>
              Membuat produk sabun cuci tangan, cuci piring, cuci baju dan permutih baju. Lalu memasarkan produk tersebut dijual minimal 10 produk setiap hari, produk tersebut bisa dijual dengan datang rumah kerumah atau tempat ke tempat ataupun bisa melalui online seperti menjual melalui Shopee, Tokopedia, dan Lazada.
            </li>

            <li>
              Lalu produk tersebut dipromosikan melalui sosial media seperti Facebook, Instagram dan Youtube.
            </li>
              
          </ul>
        </div>

        <div className="container-pengalaman">
          <p><strong>OSIS SMK Tanjung Priok 2</strong> (Jakarta, Indonesia)</p>
          <p><strong>Dokumentasi </strong> (Januari 2021 – April 2022)</p>

          <ul>
            <li>
              Membuat agenda, proposal, serta dokumen untuk melakukan kegiatan OSIS yang akan di tandatangani oleh kepala sekolah serta pembina OSIS.
            </li>

            <li>
              Melakukan dokumentasi untuk kegiatan serta mengatur jalannya kegiatan yang diadakan oleh OSIS maupun dari luar sekolah agar kegiatan tersebut berjalan dengan lancar.
            </li>
              
          </ul>
        </div>

        <div className="container-pengalaman">
          <p><strong>Pramuka SMK Tanjung Priok 2</strong> (Jakarta, Indonesia)</p>
          <p><strong>Anggota</strong> (Januari 2021 – April 2022)</p>

          <ul>
            <li>
              Diajarkan oleh pembina agar menjadi pemimpin yang disiplin, berani, tegas, terampil, taat pada sang maha kuasa, kreatif, memiliki growth-mindset, serta diajarkan untuk bekerja sama dengan regu dan kelompok persanggah.
            </li>

            <li>
              Diajarkan cara melakukan baris-berbaris, sandi-sandi, Menggunakan Kompas, Berenang, serta ilmu berkemah.
            </li>
              
          </ul>
        </div>

      </div>
    </section>
    {/* End Pengalaman */}

    {/* Projek */}
    {/* <section id="projek">
      <div className="container">
        
        <div className="col-sm">
          <h2 className="text-center">Project</h2>
          <div className="underline-txt"></div>
        </div>
        
      </div>
    </section> */}
    {/* End Projek */}

    
  </main>

  <Script type="text/javascript" src="/scripts/home.js"/>
  </>
  )
}